// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageDeleteFileACK.proto

#ifndef PROTOBUF_MessageDeleteFileACK_2eproto__INCLUDED
#define PROTOBUF_MessageDeleteFileACK_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageDeleteFileACK_2eproto();
void protobuf_AssignDesc_MessageDeleteFileACK_2eproto();
void protobuf_ShutdownFile_MessageDeleteFileACK_2eproto();

class MessageDeleteFileACK;

// ===================================================================

class MessageDeleteFileACK : public ::google::protobuf::Message {
 public:
  MessageDeleteFileACK();
  virtual ~MessageDeleteFileACK();

  MessageDeleteFileACK(const MessageDeleteFileACK& from);

  inline MessageDeleteFileACK& operator=(const MessageDeleteFileACK& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageDeleteFileACK& default_instance();

  void Swap(MessageDeleteFileACK* other);

  // implements Message ----------------------------------------------

  MessageDeleteFileACK* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageDeleteFileACK& from);
  void MergeFrom(const MessageDeleteFileACK& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 Code = 1;
  inline bool has_code() const;
  inline void clear_code();
  static const int kCodeFieldNumber = 1;
  inline ::google::protobuf::int32 code() const;
  inline void set_code(::google::protobuf::int32 value);

  // required string Message = 2;
  inline bool has_message() const;
  inline void clear_message();
  static const int kMessageFieldNumber = 2;
  inline const ::std::string& message() const;
  inline void set_message(const ::std::string& value);
  inline void set_message(const char* value);
  inline void set_message(const char* value, size_t size);
  inline ::std::string* mutable_message();
  inline ::std::string* release_message();
  inline void set_allocated_message(::std::string* message);

  // required string Path = 3;
  inline bool has_path() const;
  inline void clear_path();
  static const int kPathFieldNumber = 3;
  inline const ::std::string& path() const;
  inline void set_path(const ::std::string& value);
  inline void set_path(const char* value);
  inline void set_path(const char* value, size_t size);
  inline ::std::string* mutable_path();
  inline ::std::string* release_path();
  inline void set_allocated_path(::std::string* path);

  // @@protoc_insertion_point(class_scope:MessageDeleteFileACK)
 private:
  inline void set_has_code();
  inline void clear_has_code();
  inline void set_has_message();
  inline void clear_has_message();
  inline void set_has_path();
  inline void clear_has_path();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* message_;
  ::std::string* path_;
  ::google::protobuf::int32 code_;
  friend void  protobuf_AddDesc_MessageDeleteFileACK_2eproto();
  friend void protobuf_AssignDesc_MessageDeleteFileACK_2eproto();
  friend void protobuf_ShutdownFile_MessageDeleteFileACK_2eproto();

  void InitAsDefaultInstance();
  static MessageDeleteFileACK* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageDeleteFileACK

// required int32 Code = 1;
inline bool MessageDeleteFileACK::has_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageDeleteFileACK::set_has_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageDeleteFileACK::clear_has_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageDeleteFileACK::clear_code() {
  code_ = 0;
  clear_has_code();
}
inline ::google::protobuf::int32 MessageDeleteFileACK::code() const {
  // @@protoc_insertion_point(field_get:MessageDeleteFileACK.Code)
  return code_;
}
inline void MessageDeleteFileACK::set_code(::google::protobuf::int32 value) {
  set_has_code();
  code_ = value;
  // @@protoc_insertion_point(field_set:MessageDeleteFileACK.Code)
}

// required string Message = 2;
inline bool MessageDeleteFileACK::has_message() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageDeleteFileACK::set_has_message() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageDeleteFileACK::clear_has_message() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageDeleteFileACK::clear_message() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_->clear();
  }
  clear_has_message();
}
inline const ::std::string& MessageDeleteFileACK::message() const {
  // @@protoc_insertion_point(field_get:MessageDeleteFileACK.Message)
  return *message_;
}
inline void MessageDeleteFileACK::set_message(const ::std::string& value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set:MessageDeleteFileACK.Message)
}
inline void MessageDeleteFileACK::set_message(const char* value) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageDeleteFileACK.Message)
}
inline void MessageDeleteFileACK::set_message(const char* value, size_t size) {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  message_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageDeleteFileACK.Message)
}
inline ::std::string* MessageDeleteFileACK::mutable_message() {
  set_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    message_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageDeleteFileACK.Message)
  return message_;
}
inline ::std::string* MessageDeleteFileACK::release_message() {
  clear_has_message();
  if (message_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = message_;
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageDeleteFileACK::set_allocated_message(::std::string* message) {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (message) {
    set_has_message();
    message_ = message;
  } else {
    clear_has_message();
    message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageDeleteFileACK.Message)
}

// required string Path = 3;
inline bool MessageDeleteFileACK::has_path() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageDeleteFileACK::set_has_path() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageDeleteFileACK::clear_has_path() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageDeleteFileACK::clear_path() {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_->clear();
  }
  clear_has_path();
}
inline const ::std::string& MessageDeleteFileACK::path() const {
  // @@protoc_insertion_point(field_get:MessageDeleteFileACK.Path)
  return *path_;
}
inline void MessageDeleteFileACK::set_path(const ::std::string& value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set:MessageDeleteFileACK.Path)
}
inline void MessageDeleteFileACK::set_path(const char* value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageDeleteFileACK.Path)
}
inline void MessageDeleteFileACK::set_path(const char* value, size_t size) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageDeleteFileACK.Path)
}
inline ::std::string* MessageDeleteFileACK::mutable_path() {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageDeleteFileACK.Path)
  return path_;
}
inline ::std::string* MessageDeleteFileACK::release_path() {
  clear_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = path_;
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageDeleteFileACK::set_allocated_path(::std::string* path) {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete path_;
  }
  if (path) {
    set_has_path();
    path_ = path;
  } else {
    clear_has_path();
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageDeleteFileACK.Path)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageDeleteFileACK_2eproto__INCLUDED
