// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageDeleteBlockACK.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "MessageDeleteBlockACK.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MessageDeleteBlockACK_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessageDeleteBlockACK_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_MessageDeleteBlockACK_2eproto() {
  protobuf_AddDesc_MessageDeleteBlockACK_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "MessageDeleteBlockACK.proto");
  GOOGLE_CHECK(file != NULL);
  MessageDeleteBlockACK_descriptor_ = file->message_type(0);
  static const int MessageDeleteBlockACK_offsets_[6] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageDeleteBlockACK, code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageDeleteBlockACK, message_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageDeleteBlockACK, clientid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageDeleteBlockACK, index_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageDeleteBlockACK, path_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageDeleteBlockACK, partid_),
  };
  MessageDeleteBlockACK_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MessageDeleteBlockACK_descriptor_,
      MessageDeleteBlockACK::default_instance_,
      MessageDeleteBlockACK_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageDeleteBlockACK, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageDeleteBlockACK, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MessageDeleteBlockACK));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_MessageDeleteBlockACK_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MessageDeleteBlockACK_descriptor_, &MessageDeleteBlockACK::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_MessageDeleteBlockACK_2eproto() {
  delete MessageDeleteBlockACK::default_instance_;
  delete MessageDeleteBlockACK_reflection_;
}

void protobuf_AddDesc_MessageDeleteBlockACK_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\033MessageDeleteBlockACK.proto\"u\n\025Message"
    "DeleteBlockACK\022\014\n\004Code\030\001 \002(\005\022\017\n\007Message\030"
    "\002 \002(\t\022\020\n\010ClientId\030\003 \002(\003\022\r\n\005Index\030\004 \002(\003\022\014"
    "\n\004Path\030\005 \002(\t\022\016\n\006PartId\030\006 \002(\003", 148);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MessageDeleteBlockACK.proto", &protobuf_RegisterTypes);
  MessageDeleteBlockACK::default_instance_ = new MessageDeleteBlockACK();
  MessageDeleteBlockACK::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_MessageDeleteBlockACK_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_MessageDeleteBlockACK_2eproto {
  StaticDescriptorInitializer_MessageDeleteBlockACK_2eproto() {
    protobuf_AddDesc_MessageDeleteBlockACK_2eproto();
  }
} static_descriptor_initializer_MessageDeleteBlockACK_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MessageDeleteBlockACK::kCodeFieldNumber;
const int MessageDeleteBlockACK::kMessageFieldNumber;
const int MessageDeleteBlockACK::kClientIdFieldNumber;
const int MessageDeleteBlockACK::kIndexFieldNumber;
const int MessageDeleteBlockACK::kPathFieldNumber;
const int MessageDeleteBlockACK::kPartIdFieldNumber;
#endif  // !_MSC_VER

MessageDeleteBlockACK::MessageDeleteBlockACK()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:MessageDeleteBlockACK)
}

void MessageDeleteBlockACK::InitAsDefaultInstance() {
}

MessageDeleteBlockACK::MessageDeleteBlockACK(const MessageDeleteBlockACK& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MessageDeleteBlockACK)
}

void MessageDeleteBlockACK::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  code_ = 0;
  message_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clientid_ = GOOGLE_LONGLONG(0);
  index_ = GOOGLE_LONGLONG(0);
  path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  partid_ = GOOGLE_LONGLONG(0);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageDeleteBlockACK::~MessageDeleteBlockACK() {
  // @@protoc_insertion_point(destructor:MessageDeleteBlockACK)
  SharedDtor();
}

void MessageDeleteBlockACK::SharedDtor() {
  if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete message_;
  }
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete path_;
  }
  if (this != default_instance_) {
  }
}

void MessageDeleteBlockACK::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessageDeleteBlockACK::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageDeleteBlockACK_descriptor_;
}

const MessageDeleteBlockACK& MessageDeleteBlockACK::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_MessageDeleteBlockACK_2eproto();
  return *default_instance_;
}

MessageDeleteBlockACK* MessageDeleteBlockACK::default_instance_ = NULL;

MessageDeleteBlockACK* MessageDeleteBlockACK::New() const {
  return new MessageDeleteBlockACK;
}

void MessageDeleteBlockACK::Clear() {
#define OFFSET_OF_FIELD_(f) (reinterpret_cast<char*>(      \
  &reinterpret_cast<MessageDeleteBlockACK*>(16)->f) - \
   reinterpret_cast<char*>(16))

#define ZR_(first, last) do {                              \
    size_t f = OFFSET_OF_FIELD_(first);                    \
    size_t n = OFFSET_OF_FIELD_(last) - f + sizeof(last);  \
    ::memset(&first, 0, n);                                \
  } while (0)

  if (_has_bits_[0 / 32] & 63) {
    ZR_(clientid_, index_);
    ZR_(partid_, code_);
    if (has_message()) {
      if (message_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        message_->clear();
      }
    }
    if (has_path()) {
      if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
        path_->clear();
      }
    }
  }

#undef OFFSET_OF_FIELD_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MessageDeleteBlockACK::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MessageDeleteBlockACK)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 Code = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &code_)));
          set_has_code();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_Message;
        break;
      }

      // required string Message = 2;
      case 2: {
        if (tag == 18) {
         parse_Message:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->message().data(), this->message().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "message");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_ClientId;
        break;
      }

      // required int64 ClientId = 3;
      case 3: {
        if (tag == 24) {
         parse_ClientId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &clientid_)));
          set_has_clientid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_Index;
        break;
      }

      // required int64 Index = 4;
      case 4: {
        if (tag == 32) {
         parse_Index:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &index_)));
          set_has_index();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_Path;
        break;
      }

      // required string Path = 5;
      case 5: {
        if (tag == 42) {
         parse_Path:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_path()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->path().data(), this->path().length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "path");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(48)) goto parse_PartId;
        break;
      }

      // required int64 PartId = 6;
      case 6: {
        if (tag == 48) {
         parse_PartId:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int64, ::google::protobuf::internal::WireFormatLite::TYPE_INT64>(
                 input, &partid_)));
          set_has_partid();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MessageDeleteBlockACK)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MessageDeleteBlockACK)
  return false;
#undef DO_
}

void MessageDeleteBlockACK::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MessageDeleteBlockACK)
  // required int32 Code = 1;
  if (has_code()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->code(), output);
  }

  // required string Message = 2;
  if (has_message()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->message(), output);
  }

  // required int64 ClientId = 3;
  if (has_clientid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(3, this->clientid(), output);
  }

  // required int64 Index = 4;
  if (has_index()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(4, this->index(), output);
  }

  // required string Path = 5;
  if (has_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->path().data(), this->path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "path");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->path(), output);
  }

  // required int64 PartId = 6;
  if (has_partid()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt64(6, this->partid(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:MessageDeleteBlockACK)
}

::google::protobuf::uint8* MessageDeleteBlockACK::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:MessageDeleteBlockACK)
  // required int32 Code = 1;
  if (has_code()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->code(), target);
  }

  // required string Message = 2;
  if (has_message()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->message().data(), this->message().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->message(), target);
  }

  // required int64 ClientId = 3;
  if (has_clientid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(3, this->clientid(), target);
  }

  // required int64 Index = 4;
  if (has_index()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(4, this->index(), target);
  }

  // required string Path = 5;
  if (has_path()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->path().data(), this->path().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "path");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->path(), target);
  }

  // required int64 PartId = 6;
  if (has_partid()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArray(6, this->partid(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MessageDeleteBlockACK)
  return target;
}

int MessageDeleteBlockACK::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 Code = 1;
    if (has_code()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->code());
    }

    // required string Message = 2;
    if (has_message()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->message());
    }

    // required int64 ClientId = 3;
    if (has_clientid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->clientid());
    }

    // required int64 Index = 4;
    if (has_index()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->index());
    }

    // required string Path = 5;
    if (has_path()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->path());
    }

    // required int64 PartId = 6;
    if (has_partid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int64Size(
          this->partid());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageDeleteBlockACK::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MessageDeleteBlockACK* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MessageDeleteBlockACK*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MessageDeleteBlockACK::MergeFrom(const MessageDeleteBlockACK& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_code()) {
      set_code(from.code());
    }
    if (from.has_message()) {
      set_message(from.message());
    }
    if (from.has_clientid()) {
      set_clientid(from.clientid());
    }
    if (from.has_index()) {
      set_index(from.index());
    }
    if (from.has_path()) {
      set_path(from.path());
    }
    if (from.has_partid()) {
      set_partid(from.partid());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MessageDeleteBlockACK::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageDeleteBlockACK::CopyFrom(const MessageDeleteBlockACK& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageDeleteBlockACK::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000003f) != 0x0000003f) return false;

  return true;
}

void MessageDeleteBlockACK::Swap(MessageDeleteBlockACK* other) {
  if (other != this) {
    std::swap(code_, other->code_);
    std::swap(message_, other->message_);
    std::swap(clientid_, other->clientid_);
    std::swap(index_, other->index_);
    std::swap(path_, other->path_);
    std::swap(partid_, other->partid_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MessageDeleteBlockACK::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessageDeleteBlockACK_descriptor_;
  metadata.reflection = MessageDeleteBlockACK_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
