// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageDuplicateDataRequest.proto

#ifndef PROTOBUF_MessageDuplicateDataRequest_2eproto__INCLUDED
#define PROTOBUF_MessageDuplicateDataRequest_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageDuplicateDataRequest_2eproto();
void protobuf_AssignDesc_MessageDuplicateDataRequest_2eproto();
void protobuf_ShutdownFile_MessageDuplicateDataRequest_2eproto();

class MessageDuplicateDataRequest;

// ===================================================================

class MessageDuplicateDataRequest : public ::google::protobuf::Message {
 public:
  MessageDuplicateDataRequest();
  virtual ~MessageDuplicateDataRequest();

  MessageDuplicateDataRequest(const MessageDuplicateDataRequest& from);

  inline MessageDuplicateDataRequest& operator=(const MessageDuplicateDataRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageDuplicateDataRequest& default_instance();

  void Swap(MessageDuplicateDataRequest* other);

  // implements Message ----------------------------------------------

  MessageDuplicateDataRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageDuplicateDataRequest& from);
  void MergeFrom(const MessageDuplicateDataRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string Token = 1;
  inline bool has_token() const;
  inline void clear_token();
  static const int kTokenFieldNumber = 1;
  inline const ::std::string& token() const;
  inline void set_token(const ::std::string& value);
  inline void set_token(const char* value);
  inline void set_token(const char* value, size_t size);
  inline ::std::string* mutable_token();
  inline ::std::string* release_token();
  inline void set_allocated_token(::std::string* token);

  // required int64 Index = 2;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 2;
  inline ::google::protobuf::int64 index() const;
  inline void set_index(::google::protobuf::int64 value);

  // required int64 Offset = 3;
  inline bool has_offset() const;
  inline void clear_offset();
  static const int kOffsetFieldNumber = 3;
  inline ::google::protobuf::int64 offset() const;
  inline void set_offset(::google::protobuf::int64 value);

  // required int64 Size = 4;
  inline bool has_size() const;
  inline void clear_size();
  static const int kSizeFieldNumber = 4;
  inline ::google::protobuf::int64 size() const;
  inline void set_size(::google::protobuf::int64 value);

  // required int64 SessionId = 5;
  inline bool has_sessionid() const;
  inline void clear_sessionid();
  static const int kSessionIdFieldNumber = 5;
  inline ::google::protobuf::int64 sessionid() const;
  inline void set_sessionid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MessageDuplicateDataRequest)
 private:
  inline void set_has_token();
  inline void clear_has_token();
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_offset();
  inline void clear_has_offset();
  inline void set_has_size();
  inline void clear_has_size();
  inline void set_has_sessionid();
  inline void clear_has_sessionid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* token_;
  ::google::protobuf::int64 index_;
  ::google::protobuf::int64 offset_;
  ::google::protobuf::int64 size_;
  ::google::protobuf::int64 sessionid_;
  friend void  protobuf_AddDesc_MessageDuplicateDataRequest_2eproto();
  friend void protobuf_AssignDesc_MessageDuplicateDataRequest_2eproto();
  friend void protobuf_ShutdownFile_MessageDuplicateDataRequest_2eproto();

  void InitAsDefaultInstance();
  static MessageDuplicateDataRequest* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageDuplicateDataRequest

// required string Token = 1;
inline bool MessageDuplicateDataRequest::has_token() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageDuplicateDataRequest::set_has_token() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageDuplicateDataRequest::clear_has_token() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageDuplicateDataRequest::clear_token() {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_->clear();
  }
  clear_has_token();
}
inline const ::std::string& MessageDuplicateDataRequest::token() const {
  // @@protoc_insertion_point(field_get:MessageDuplicateDataRequest.Token)
  return *token_;
}
inline void MessageDuplicateDataRequest::set_token(const ::std::string& value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set:MessageDuplicateDataRequest.Token)
}
inline void MessageDuplicateDataRequest::set_token(const char* value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageDuplicateDataRequest.Token)
}
inline void MessageDuplicateDataRequest::set_token(const char* value, size_t size) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageDuplicateDataRequest.Token)
}
inline ::std::string* MessageDuplicateDataRequest::mutable_token() {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageDuplicateDataRequest.Token)
  return token_;
}
inline ::std::string* MessageDuplicateDataRequest::release_token() {
  clear_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = token_;
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageDuplicateDataRequest::set_allocated_token(::std::string* token) {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete token_;
  }
  if (token) {
    set_has_token();
    token_ = token;
  } else {
    clear_has_token();
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageDuplicateDataRequest.Token)
}

// required int64 Index = 2;
inline bool MessageDuplicateDataRequest::has_index() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageDuplicateDataRequest::set_has_index() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageDuplicateDataRequest::clear_has_index() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageDuplicateDataRequest::clear_index() {
  index_ = GOOGLE_LONGLONG(0);
  clear_has_index();
}
inline ::google::protobuf::int64 MessageDuplicateDataRequest::index() const {
  // @@protoc_insertion_point(field_get:MessageDuplicateDataRequest.Index)
  return index_;
}
inline void MessageDuplicateDataRequest::set_index(::google::protobuf::int64 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:MessageDuplicateDataRequest.Index)
}

// required int64 Offset = 3;
inline bool MessageDuplicateDataRequest::has_offset() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageDuplicateDataRequest::set_has_offset() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageDuplicateDataRequest::clear_has_offset() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageDuplicateDataRequest::clear_offset() {
  offset_ = GOOGLE_LONGLONG(0);
  clear_has_offset();
}
inline ::google::protobuf::int64 MessageDuplicateDataRequest::offset() const {
  // @@protoc_insertion_point(field_get:MessageDuplicateDataRequest.Offset)
  return offset_;
}
inline void MessageDuplicateDataRequest::set_offset(::google::protobuf::int64 value) {
  set_has_offset();
  offset_ = value;
  // @@protoc_insertion_point(field_set:MessageDuplicateDataRequest.Offset)
}

// required int64 Size = 4;
inline bool MessageDuplicateDataRequest::has_size() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MessageDuplicateDataRequest::set_has_size() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MessageDuplicateDataRequest::clear_has_size() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MessageDuplicateDataRequest::clear_size() {
  size_ = GOOGLE_LONGLONG(0);
  clear_has_size();
}
inline ::google::protobuf::int64 MessageDuplicateDataRequest::size() const {
  // @@protoc_insertion_point(field_get:MessageDuplicateDataRequest.Size)
  return size_;
}
inline void MessageDuplicateDataRequest::set_size(::google::protobuf::int64 value) {
  set_has_size();
  size_ = value;
  // @@protoc_insertion_point(field_set:MessageDuplicateDataRequest.Size)
}

// required int64 SessionId = 5;
inline bool MessageDuplicateDataRequest::has_sessionid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MessageDuplicateDataRequest::set_has_sessionid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MessageDuplicateDataRequest::clear_has_sessionid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MessageDuplicateDataRequest::clear_sessionid() {
  sessionid_ = GOOGLE_LONGLONG(0);
  clear_has_sessionid();
}
inline ::google::protobuf::int64 MessageDuplicateDataRequest::sessionid() const {
  // @@protoc_insertion_point(field_get:MessageDuplicateDataRequest.SessionId)
  return sessionid_;
}
inline void MessageDuplicateDataRequest::set_sessionid(::google::protobuf::int64 value) {
  set_has_sessionid();
  sessionid_ = value;
  // @@protoc_insertion_point(field_set:MessageDuplicateDataRequest.SessionId)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageDuplicateDataRequest_2eproto__INCLUDED
