// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MessageDuplicateBlock.proto

#ifndef PROTOBUF_MessageDuplicateBlock_2eproto__INCLUDED
#define PROTOBUF_MessageDuplicateBlock_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_MessageDuplicateBlock_2eproto();
void protobuf_AssignDesc_MessageDuplicateBlock_2eproto();
void protobuf_ShutdownFile_MessageDuplicateBlock_2eproto();

class MessageDuplicateBlock;

// ===================================================================

class MessageDuplicateBlock : public ::google::protobuf::Message {
 public:
  MessageDuplicateBlock();
  virtual ~MessageDuplicateBlock();

  MessageDuplicateBlock(const MessageDuplicateBlock& from);

  inline MessageDuplicateBlock& operator=(const MessageDuplicateBlock& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const MessageDuplicateBlock& default_instance();

  void Swap(MessageDuplicateBlock* other);

  // implements Message ----------------------------------------------

  MessageDuplicateBlock* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MessageDuplicateBlock& from);
  void MergeFrom(const MessageDuplicateBlock& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string Token = 1;
  inline bool has_token() const;
  inline void clear_token();
  static const int kTokenFieldNumber = 1;
  inline const ::std::string& token() const;
  inline void set_token(const ::std::string& value);
  inline void set_token(const char* value);
  inline void set_token(const char* value, size_t size);
  inline ::std::string* mutable_token();
  inline ::std::string* release_token();
  inline void set_allocated_token(::std::string* token);

  // required string Address = 2;
  inline bool has_address() const;
  inline void clear_address();
  static const int kAddressFieldNumber = 2;
  inline const ::std::string& address() const;
  inline void set_address(const ::std::string& value);
  inline void set_address(const char* value);
  inline void set_address(const char* value, size_t size);
  inline ::std::string* mutable_address();
  inline ::std::string* release_address();
  inline void set_allocated_address(::std::string* address);

  // required int32 Port = 3;
  inline bool has_port() const;
  inline void clear_port();
  static const int kPortFieldNumber = 3;
  inline ::google::protobuf::int32 port() const;
  inline void set_port(::google::protobuf::int32 value);

  // required int64 Index = 4;
  inline bool has_index() const;
  inline void clear_index();
  static const int kIndexFieldNumber = 4;
  inline ::google::protobuf::int64 index() const;
  inline void set_index(::google::protobuf::int64 value);

  // required int64 PartId = 5;
  inline bool has_partid() const;
  inline void clear_partid();
  static const int kPartIdFieldNumber = 5;
  inline ::google::protobuf::int64 partid() const;
  inline void set_partid(::google::protobuf::int64 value);

  // required int64 FileOffset = 6;
  inline bool has_fileoffset() const;
  inline void clear_fileoffset();
  static const int kFileOffsetFieldNumber = 6;
  inline ::google::protobuf::int64 fileoffset() const;
  inline void set_fileoffset(::google::protobuf::int64 value);

  // required string Path = 7;
  inline bool has_path() const;
  inline void clear_path();
  static const int kPathFieldNumber = 7;
  inline const ::std::string& path() const;
  inline void set_path(const ::std::string& value);
  inline void set_path(const char* value);
  inline void set_path(const char* value, size_t size);
  inline ::std::string* mutable_path();
  inline ::std::string* release_path();
  inline void set_allocated_path(::std::string* path);

  // @@protoc_insertion_point(class_scope:MessageDuplicateBlock)
 private:
  inline void set_has_token();
  inline void clear_has_token();
  inline void set_has_address();
  inline void clear_has_address();
  inline void set_has_port();
  inline void clear_has_port();
  inline void set_has_index();
  inline void clear_has_index();
  inline void set_has_partid();
  inline void clear_has_partid();
  inline void set_has_fileoffset();
  inline void clear_has_fileoffset();
  inline void set_has_path();
  inline void clear_has_path();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::std::string* token_;
  ::std::string* address_;
  ::google::protobuf::int64 index_;
  ::google::protobuf::int64 partid_;
  ::google::protobuf::int64 fileoffset_;
  ::std::string* path_;
  ::google::protobuf::int32 port_;
  friend void  protobuf_AddDesc_MessageDuplicateBlock_2eproto();
  friend void protobuf_AssignDesc_MessageDuplicateBlock_2eproto();
  friend void protobuf_ShutdownFile_MessageDuplicateBlock_2eproto();

  void InitAsDefaultInstance();
  static MessageDuplicateBlock* default_instance_;
};
// ===================================================================


// ===================================================================

// MessageDuplicateBlock

// required string Token = 1;
inline bool MessageDuplicateBlock::has_token() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MessageDuplicateBlock::set_has_token() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MessageDuplicateBlock::clear_has_token() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MessageDuplicateBlock::clear_token() {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_->clear();
  }
  clear_has_token();
}
inline const ::std::string& MessageDuplicateBlock::token() const {
  // @@protoc_insertion_point(field_get:MessageDuplicateBlock.Token)
  return *token_;
}
inline void MessageDuplicateBlock::set_token(const ::std::string& value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set:MessageDuplicateBlock.Token)
}
inline void MessageDuplicateBlock::set_token(const char* value) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageDuplicateBlock.Token)
}
inline void MessageDuplicateBlock::set_token(const char* value, size_t size) {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  token_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageDuplicateBlock.Token)
}
inline ::std::string* MessageDuplicateBlock::mutable_token() {
  set_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    token_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageDuplicateBlock.Token)
  return token_;
}
inline ::std::string* MessageDuplicateBlock::release_token() {
  clear_has_token();
  if (token_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = token_;
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageDuplicateBlock::set_allocated_token(::std::string* token) {
  if (token_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete token_;
  }
  if (token) {
    set_has_token();
    token_ = token;
  } else {
    clear_has_token();
    token_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageDuplicateBlock.Token)
}

// required string Address = 2;
inline bool MessageDuplicateBlock::has_address() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MessageDuplicateBlock::set_has_address() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MessageDuplicateBlock::clear_has_address() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MessageDuplicateBlock::clear_address() {
  if (address_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    address_->clear();
  }
  clear_has_address();
}
inline const ::std::string& MessageDuplicateBlock::address() const {
  // @@protoc_insertion_point(field_get:MessageDuplicateBlock.Address)
  return *address_;
}
inline void MessageDuplicateBlock::set_address(const ::std::string& value) {
  set_has_address();
  if (address_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    address_ = new ::std::string;
  }
  address_->assign(value);
  // @@protoc_insertion_point(field_set:MessageDuplicateBlock.Address)
}
inline void MessageDuplicateBlock::set_address(const char* value) {
  set_has_address();
  if (address_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    address_ = new ::std::string;
  }
  address_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageDuplicateBlock.Address)
}
inline void MessageDuplicateBlock::set_address(const char* value, size_t size) {
  set_has_address();
  if (address_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    address_ = new ::std::string;
  }
  address_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageDuplicateBlock.Address)
}
inline ::std::string* MessageDuplicateBlock::mutable_address() {
  set_has_address();
  if (address_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    address_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageDuplicateBlock.Address)
  return address_;
}
inline ::std::string* MessageDuplicateBlock::release_address() {
  clear_has_address();
  if (address_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = address_;
    address_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageDuplicateBlock::set_allocated_address(::std::string* address) {
  if (address_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete address_;
  }
  if (address) {
    set_has_address();
    address_ = address;
  } else {
    clear_has_address();
    address_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageDuplicateBlock.Address)
}

// required int32 Port = 3;
inline bool MessageDuplicateBlock::has_port() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MessageDuplicateBlock::set_has_port() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MessageDuplicateBlock::clear_has_port() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MessageDuplicateBlock::clear_port() {
  port_ = 0;
  clear_has_port();
}
inline ::google::protobuf::int32 MessageDuplicateBlock::port() const {
  // @@protoc_insertion_point(field_get:MessageDuplicateBlock.Port)
  return port_;
}
inline void MessageDuplicateBlock::set_port(::google::protobuf::int32 value) {
  set_has_port();
  port_ = value;
  // @@protoc_insertion_point(field_set:MessageDuplicateBlock.Port)
}

// required int64 Index = 4;
inline bool MessageDuplicateBlock::has_index() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MessageDuplicateBlock::set_has_index() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MessageDuplicateBlock::clear_has_index() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MessageDuplicateBlock::clear_index() {
  index_ = GOOGLE_LONGLONG(0);
  clear_has_index();
}
inline ::google::protobuf::int64 MessageDuplicateBlock::index() const {
  // @@protoc_insertion_point(field_get:MessageDuplicateBlock.Index)
  return index_;
}
inline void MessageDuplicateBlock::set_index(::google::protobuf::int64 value) {
  set_has_index();
  index_ = value;
  // @@protoc_insertion_point(field_set:MessageDuplicateBlock.Index)
}

// required int64 PartId = 5;
inline bool MessageDuplicateBlock::has_partid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void MessageDuplicateBlock::set_has_partid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void MessageDuplicateBlock::clear_has_partid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void MessageDuplicateBlock::clear_partid() {
  partid_ = GOOGLE_LONGLONG(0);
  clear_has_partid();
}
inline ::google::protobuf::int64 MessageDuplicateBlock::partid() const {
  // @@protoc_insertion_point(field_get:MessageDuplicateBlock.PartId)
  return partid_;
}
inline void MessageDuplicateBlock::set_partid(::google::protobuf::int64 value) {
  set_has_partid();
  partid_ = value;
  // @@protoc_insertion_point(field_set:MessageDuplicateBlock.PartId)
}

// required int64 FileOffset = 6;
inline bool MessageDuplicateBlock::has_fileoffset() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void MessageDuplicateBlock::set_has_fileoffset() {
  _has_bits_[0] |= 0x00000020u;
}
inline void MessageDuplicateBlock::clear_has_fileoffset() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void MessageDuplicateBlock::clear_fileoffset() {
  fileoffset_ = GOOGLE_LONGLONG(0);
  clear_has_fileoffset();
}
inline ::google::protobuf::int64 MessageDuplicateBlock::fileoffset() const {
  // @@protoc_insertion_point(field_get:MessageDuplicateBlock.FileOffset)
  return fileoffset_;
}
inline void MessageDuplicateBlock::set_fileoffset(::google::protobuf::int64 value) {
  set_has_fileoffset();
  fileoffset_ = value;
  // @@protoc_insertion_point(field_set:MessageDuplicateBlock.FileOffset)
}

// required string Path = 7;
inline bool MessageDuplicateBlock::has_path() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void MessageDuplicateBlock::set_has_path() {
  _has_bits_[0] |= 0x00000040u;
}
inline void MessageDuplicateBlock::clear_has_path() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void MessageDuplicateBlock::clear_path() {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_->clear();
  }
  clear_has_path();
}
inline const ::std::string& MessageDuplicateBlock::path() const {
  // @@protoc_insertion_point(field_get:MessageDuplicateBlock.Path)
  return *path_;
}
inline void MessageDuplicateBlock::set_path(const ::std::string& value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set:MessageDuplicateBlock.Path)
}
inline void MessageDuplicateBlock::set_path(const char* value) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(value);
  // @@protoc_insertion_point(field_set_char:MessageDuplicateBlock.Path)
}
inline void MessageDuplicateBlock::set_path(const char* value, size_t size) {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  path_->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:MessageDuplicateBlock.Path)
}
inline ::std::string* MessageDuplicateBlock::mutable_path() {
  set_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    path_ = new ::std::string;
  }
  // @@protoc_insertion_point(field_mutable:MessageDuplicateBlock.Path)
  return path_;
}
inline ::std::string* MessageDuplicateBlock::release_path() {
  clear_has_path();
  if (path_ == &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    return NULL;
  } else {
    ::std::string* temp = path_;
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    return temp;
  }
}
inline void MessageDuplicateBlock::set_allocated_path(::std::string* path) {
  if (path_ != &::google::protobuf::internal::GetEmptyStringAlreadyInited()) {
    delete path_;
  }
  if (path) {
    set_has_path();
    path_ = path;
  } else {
    clear_has_path();
    path_ = const_cast< ::std::string*>(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_set_allocated:MessageDuplicateBlock.Path)
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MessageDuplicateBlock_2eproto__INCLUDED
